name: 01_test
on:
  workflow_dispatch:
jobs:
  test_job_1:
    name: Test Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (pwd)
        run: pwd

      - name: Step 2 (lsb_release -a)
        run: lsb_release -a

      - name: Step 3 (ls -la /)
        run: ls -la /

      - name: Step 4 (whoami)
        run: whoami

      - name: Step 5 (sudo apt install nginx)
        run: sudo apt install nginx


