name: 01_test
on:
  workflow_dispatch:
jobs:
  test_job_1:
    name: Test Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (PWD)
        run: pwd

      - name: Step 2 (LS)
        run: ls -l


