# https://github.com/appleboy/ssh-action

name: 05_simple_deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to Demo 1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: demo_1
          key: ${{secrets.PRIVATE_KEY}}
          script: "/usr/local/bin/devops/deploy/deploy.sh"
