name: 08_php_psalm
#on: [ push, pull_request ]
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  PHPMD:
    name: Run php psalm
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, opcache, sodium

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      # https://github.com/marketplace/actions/psalm-static-analysis-for-php
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_ignore_platform_reqs: true
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
