name: 12_build_test_deploy

on: [ push, pull_request ]
#on:
#  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: checkout, build, sign, scan, and archive code
    runs-on: ubuntu-latest
    outputs:
      version_str: ${{ steps.create_zip_file.outputs.version }}
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: phpmd

      - name: Run PHPMD
        run: phpmd . sarif codesize --reportfile phpmd-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: phpmd-results.sarif

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Sign the code
        run: |
          sudo apt install md5deep
          php artisan app:sign-code

      - name: Create zip file
        id: create_zip_file
        run: |
          date_string=$(date +"%Y-%m-%d-%H-%M-%S")
          git_short_sha=${GITHUB_SHA::7}
          version="$date_string-$git_short_sha"
          zip_file_name="build-$version.zip"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "zip_file_name=$zip_file_name" >> $GITHUB_OUTPUT
          echo $version
          mkdir -p dist
          zip -9 -rq dist/$zip_file_name . -x \*.git\* -x \*.github\* -x public/app/mocks\* -x bin/template_creator/*.tar -x node_modules/laravel-elixir\*

      # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
      - name: Archive production artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.create_zip_file.outputs.version }}
          path: |
            dist

  test:
    name: download, unpack, setup test env, run tests
    runs-on: ubuntu-latest
    needs: [ build ]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      VERSION_STR: ${{needs.build.outputs.version_str}}

    steps:
      - name: Show version string
        run: echo ${{ env.VERSION_STR }}

      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.VERSION_STR }}

      - name: Unzip the archive
        run: |
          unzip -q build*.zip
          ls -la
          rm -rf build*.zip

      # https://github.com/shivammathur/setup-php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Run Test suite
        run: php artisan test

  deploy:
    name: download, scp, deploy
    runs-on: ubuntu-latest
    needs: [ build, test ]

    env:
      VERSION_STR: ${{needs.build.outputs.version_str}}

    steps:
      - name: Show version string
        run: echo ${{ env.VERSION_STR }}

      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.VERSION_STR }}

      - name: Ensure Download Exists
        run: |
          ls -la

      - name: SCP the archive to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: demo_1
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "build*.zip"
          target: /home/demo_1/deployments

      - name: Deploy the archive
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: demo_1
          key: ${{ secrets.PRIVATE_KEY }}
          script: "/usr/local/bin/devops/deploy/deploy.sh"


