name: 12_build_test_deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version_str: ${{ steps.create_zip_file.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Create zip file
        id: create_zip_file
        run: |
          date_string=$(date +"%Y-%m-%d-%H-%M-%S")
          git_short_sha=${GITHUB_SHA::7}
          version="$date_string-$git_short_sha"
          zip_file_name="build-$version.zip"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "zip_file_name=$zip_file_name" >> $GITHUB_OUTPUT
          echo $version
          mkdir -p dist
          zip -9 -rq dist/$zip_file_name . -x \*.git\* -x \*.github\* -x public/app/mocks\* -x bin/template_creator/*.tar -x node_modules/laravel-elixir\*

      # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
      - name: Archive production artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.create_zip_file.outputs.version }}
          path: |
            dist

  test:
    runs-on: ubuntu-latest
    needs: [ build ]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      VERSION_STR: ${{needs.build.outputs.version_str}}
    steps:

      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.VERSION_STR }}

      - name: Unzip the archive
        run: |
          unzip -q build*.zip
          ls -la
          rm -rf build*.zip

      # https://github.com/shivammathur/setup-php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Run Test suite
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    env:
      VERSION_STR: ${{needs.build.outputs.version_str}}

    steps:

      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.VERSION_STR }}

      - name: SCP the archive to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 54.234.109.36
          username: demo_1
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "build*.zip"
          target: /home/demo_1/deployments

