name: complex_workflow
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Run Test suite
        run: php artisan test


  something_that_fails:
    name: Something that fails
    runs-on: ubuntu-latest

    steps:
      - name: Print Working Directory
        run: pwd

      - name: Should Fail
        run: this is a command that should fail

      - name: List all files in current directory
        run: ls -a

  php_md:
    name: Run PHPMD scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: phpmd

      - name: Run PHPMD
        run: phpmd . sarif codesize --reportfile phpmd-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true

  deploy:
    name: Deploy to Demo 1
    runs-on: ubuntu-latest
    needs: [ test, php_md, something_that_fails ]
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/demo_1.key
          chmod 600 ~/.ssh/demo_1.key
          cat >>~/.ssh/config <<END
            Host demo_1
            HostName 54.234.109.36
            User demo_1
            IdentityFile ~/.ssh/demo_1.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy
        run: ssh demo_1 '/usr/local/bin/devops/deploy/deploy.sh'

      - name: Sign The Code
        run: ssh demo_1 'cd ~/deployments/current && php artisan app:sign-code'
