name: simple_deploy_with_built_in_ssh
on: [ push, pull_request ]
jobs:
  deploy:
    name: Deploy to Demo 1
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/demo_1.key
          chmod 600 ~/.ssh/demo_1.key
          cat >>~/.ssh/config <<END
            Host demo_1
            HostName 54.234.109.36
            User demo_1
            IdentityFile ~/.ssh/demo_1.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy
        run: ssh demo_1 'source ~/.bashrc && pwd && deploy'
